### ISSUE TITLE
DESeq2' has no attribute 'counts

### ISSUE THREAD

**Issue by QUEST2179** [wckdouglas/diffexpr#1]
Dear developer,

I encountered this problem and couldn't solved myself even I googled for a long time. I am not a programmer, Could you please help? Thanks!

If I comment out this line self.normalized_count_matrix = deseq.counts(self.dds, normalized=True), it runs fine. 

I am using rpy2-3.2.7-py3.7

File "py_deseq.py", line 92, in testCountMatrix
    testDE.run_deseq()
  File "py_deseq.py", line 59, in run_deseq
    self.normalized_count_matrix = deseq.counts(self.dds, normalized=True)
AttributeError: module 'DESeq2' has no attribute 'counts'

**Comment by wckdouglas** [comment]
Hi @QUEST2179 I am guessing you are using an older version of the code? [Line 59](https://github.com/wckdouglas/diffexpr/blob/master/diffexpr/py_deseq.py#L59) now doesn't seem to be the same as what you have in the error message.

But anyways, I think you maybe able to fix that by modifying the line to:
```
self.normalized_count_matrix = deseq.counts_DESeqDataSet(self.dds, normalized=True)
```

Please let me know if that works!
