### ISSUE TITLE
Variance stablilizing transform function

### ISSUE THREAD

**Issue by victorsanchezarevalo** [wckdouglas/diffexpr#10]
Hi

I have a doubt, I would like to transform count data using the variance stablilizing transform function from DESeq2, Is it possible?

Thanks a lot!

Best

Victor

**Comment by wckdouglas** [comment]
should be possible! I'll track the work at #11

**Comment by wckdouglas** [comment]
Hi @victorsanchezarevalo, I have added the feature into the `master` branch now, see if [this](https://github.com/wckdouglas/diffexpr/blob/92197c85674ed7498bcfeeb30db0ea7c884358e5/diffexpr/py_deseq.py#L191-L233) works for you

**Comment by victorsanchezarevalo** [comment]
Great! I will try.

Thanks a lot!

Victor

**Comment by wckdouglas** [comment]
Closing this for now, feel free to file another issue or making a PR (even better 🥳 ) if you run into anything!
