### ISSUE TITLE
Can't load DESeq2 due to openblas

### ISSUE THREAD

**Issue by jvivian-atreca** [wckdouglas/diffexpr#2]
Thanks for sharing this,

At one point I got this to work but am now running into an error even with a fresh conda install.

```
Error: package or namespace load failed for ‘DESeq2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/jvivian/anaconda3/envs/deseq2/lib/R/library/DESeq2/libs/DESeq2.dylib':
  dlopen(/Users/jvivian/anaconda3/envs/deseq2/lib/R/library/DESeq2/libs/DESeq2.dylib, 6): Library not loaded: @rpath/libopenblasp-r0.3.7.dylib
  Referenced from: /Users/jvivian/anaconda3/envs/deseq2/lib/R/library/DESeq2/libs/DESeq2.dylib
  Reason: image not found
```

Installing openblas or libopenblas doesn't fix it and while I can find the path to `libopenblasp-r0.3.7.dylib` in `envs/deseq2/lib/`, linking it into the R library doesn't correct it either.

**Comment by wckdouglas** [comment]
@jvivian-atreca Thank you for reporting this!

I think this is a DESeq2 package problem in R, do you see the same if you do ```library(DESeq2)``` in R environment?:

**Comment by wckdouglas** [comment]
@jvivian-atreca so I just tried everything in a fresh conda install today, I think bioconductor-deseq2 is giving trouble. I solved it by manually installing DESeq2 in R using BiocManager:

```
conda config --add channels r
conda config --add channels bioconda
conda config --add channels auto
conda config --add channels conda-forge

conda create -q -n diffexpr python=3.6
      pandas tzlocal rpy2 biopython ReportLab pytest-cov
Rscript setup.R #to install DESeq2 correctly 
python setup.py instal
```

**Comment by jvivian-atreca** [comment]
@wckdouglas — Thank you for taking the time to dig into this! I'll give it a try when I next need to run DESeq2.

**Comment by wckdouglas** [comment]
@jvivian-atreca please let me know how if it works for you! :)
