### ISSUE TITLE
Implement Parallelization with BiocParallel

### ISSUE THREAD

**Issue by nolanmaier** [wckdouglas/diffexpr#20]
Three of the core DESeq functions ported in this package (`run_deseq`, `get_deseq_result`, and `lfcShrink`) can take advantage of parallelization according to the [DESeq vignette](https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#speed-up-and-parallelization-thoughts). 

I can get this to work with the following code block:
```
threads = 6
multicore = importr('BiocParallel')
multicore.register(multicore.MulticoreParam(threads))
```
Now `run_deseq(parallel=True)` will use 6 workers.

I am not sure the best way to implement this in the package to allow the user to indicate how many threads they want to use.

I think `lfcShrink` is not currently set up to take `**kwargs`, which may need to be fixed before the user can pass `parallel=True`

**Comment by wckdouglas** [comment]
Hi @nolanmaier, thanks for the suggestion and the tested solution! Do you wanna take a look at this [branch](https://github.com/wckdouglas/diffexpr/pull/21), I think that'd work, you'll just need to supply a `threads` parameter when you create the `py_DESeq2` object:

```python
dds = py_DESeq2(
    count_matrix = df,
    design_matrix = sample_df,
    design_formula = '~ treatment',
    gene_column = 'id', 
    threads=6
)   
dds.run_deseq() 
``` 

Let me know what you think!

**Comment by wckdouglas** [comment]
Closing as #21 is merged
