### ISSUE TITLE
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'

### ISSUE THREAD

**Issue by dexter960** [wckdouglas/diffexpr#3]
i'm trying to run DESeq2 on mu dataset but following error keeps popping up.
please someone help me !
i already install setup.py script
Can someone tell me where is the root problem, as I'm new to analysis part.
i have the latest version of rpy2 3.3.1 and installed using conda and pip. 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/65973954/83054550-35589300-a070-11ea-8e5d-1cef51d70472.png">
while seeing in the directory of the pandas2ri it seems they have deprecated the py2ri.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/65973954/83054803-984a2a00-a070-11ea-9ebe-d507e28c157d.png">

 now the real problem begins. what  attribute should i import so that this script run properly .
which verssion of python and rpy2 required so that it can work perfectly

**Comment by wckdouglas** [comment]
Hi @dexter960, Thanks for the great question!

so rpy2 indeed made some [break changes](https://bitbucket.org/rpy2/rpy2/issues/526/rpy2robjectspandas2ri-has-no-attribute) after 3.0.0, and I have updated accordingly using the [new conversion system](https://rpy2.github.io/doc/v3.0.x/html/robjects_convert.html).

Please clone the latest code and see if it works!
