### ISSUE TITLE
Ordering within contrast

### ISSUE THREAD

**Issue by jphfisher** [wckdouglas/diffexpr#4]
Hey - thanks for making this.
I just wanted to check re: ordering when running the contrast - in DESeq2 it advises releveling to ensure that you always get a Log2FoldChange from B/A, given that R likes things in alphabetical order.

Does the python version follow the same alphabetical system or will it always do:
dds.get_deseq_result(contrast = ['sample','treatment','control'])?

BW
J

**Comment by wckdouglas** [comment]
Thanks for asking! The python version should be following exactly what R does, because this is just a wrapper in python to run DESeq2 in R. With that said, I think it's safer to always specify the ```contrast``` argument.
