### ISSUE TITLE
KeyError: "'str2lang' not found"

### ISSUE THREAD

**Issue by nitishkumarmishra** [wckdouglas/diffexpr#5]
Hi,
When I am using this part of the code, I am getting error- KeyError: "'str2lang' not found"

`from diffexpr.py_deseq import py_DESeq2

dds = py_DESeq2(count_matrix = df,
               design_matrix = sample_df,
               design_formula = '~ replicate + sample',
               gene_column = 'id') # <- telling DESeq2 this should be the gene ID column
    
dds.run_deseq() 
dds.get_deseq_result(contrast = ['sample','B','A'])
res = dds.deseq_result 
res.head()`
![Slide1](https://user-images.githubusercontent.com/11510706/87236248-6684ec80-c3ac-11ea-9bde-ceaed4b6a79b.JPG)
![Slide2](https://user-images.githubusercontent.com/11510706/87236249-671d8300-c3ac-11ea-84b4-ba9377820d4e.JPG)

**Comment by nitishkumarmishra** [comment]
Hi,
I was using on centos server, when I used it on another Linux server it's working. I think there is some issue with rpy2 latest version.

Thanks
Nitish

**Comment by wckdouglas** [comment]
Hi @nitishkumarmishra, sorry I just see this. I agree this is likely a rpy2 version issue. Do you mind letting me know the versions you have tried, so we can leave a record of what's been tried? Thanks!
