### ISSUE TITLE
type='apeglm' requires installing the Bioconductor package 'apeglm'

### ISSUE THREAD

**Issue by oseias-r-junior** [wckdouglas/diffexpr#7]
Hello, 

I'm using differexpr with jupyter and also inside WSL. I have ran half of the example you have provided. But for this step:

```
# from the last cell, we see the arrangement of coefficients, 
# so that we can now use "coef" for lfcShrink
# the comparison we want to focus on is 'sample_B_vs_A', so coef = 4 will be used
lfc_res = dds.lfcShrink(coef=4, method='apeglm')
lfc_res.head()
```

I have the following output:
```
RRuntimeError: Error in (function (dds, coef, contrast, res, type = c("normal", "apeglm",  : 
  type='apeglm' requires installing the Bioconductor package 'apeglm'
```
I try to find a way to install it in the command line but without success. I have downloaded the git version of apelgm, but I'm not sure if there is a way to build/install/make for it. So, is not working yet.
Is there some shortcut for doing it inside diffexpr pipeline? (like some library import?)
Thanks in advance!

**Comment by wckdouglas** [comment]
Hi @oseias-r-junior, I think this is something you can install within the R console (you can get inside R console by typing ```r``` in terminal) and install ```apeglm``` by:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("apeglm")
```

Let me know if that works for you!

**Comment by oseias-r-junior** [comment]
> Hi @oseias-r-junior, I think this is something you can install within the R console (you can get inside R console by typing `r` in terminal) and install `apeglm` by:
> 
> ```
> if (!requireNamespace("BiocManager", quietly = TRUE))
>     install.packages("BiocManager")
> 
> BiocManager::install("apeglm")
> ```
> 
> Let me know if that works for you!

Hi @wckdouglas, thanks for answering me so fastly.  
So, I tried it, but as I am working in a python3 jupyter notebook I believe apeglm must be provided for python "to see it" as well. 
I'm trying to install apeglm in ubuntu command line using anaconda (https://anaconda.org/bioconda/bioconductor-apeglm), but even if I do that using a python=3.8 environment I receive this as output:

```
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
python=3.8 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<7.0a0']
python=3.8 -> readline[version='>=7.0,<8.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0']

Package xz conflicts for:
bioconductor-apeglm -> r-base[version='>=3.5.1,<3.5.2.0a0'] -> xz[version='5.2.*|>=5.2.4,<6.0a0']
python=3.8 -> xz[version='>=5.2.4,<6.0a0|>=5.2.5,<6.0a0']

Package libstdcxx-ng conflicts for:
python=3.8 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
python=3.8 -> libstdcxx-ng[version='>=7.3.0|>=7.5.0']

Package libgcc-ng conflicts for:
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - feature:|@/linux-64::__glibc==2.27=0
  - bioconductor-apeglm -> libgcc-ng[version='>=4.9'] -> __glibc[version='>=2.17']

Your installed version is: 2.27
```   

I saw some related issues for other tools, but I don't know how to adjust the commands for my own situation with apeglm. Here is: (https://github.com/rapidsai/clx/issues/259). Let me know, please, if you possibly know that. I also made this question for apeglm developer (https://github.com/azhu513/apeglm/issues/2). So, if you think you can not help me you can close this issue. 
Thanks again!

**Comment by wckdouglas** [comment]
ummmmm, so under the hood, ```diffexpr``` actually call ```R``` from the system out side of python environment, so I'm guessing you installed apeglm in one of the multiple ```R``` in the system? It sounds like you at least have ```R``` installed from conda, by any chance there's also a ```R``` installation from [CRAN](https://cran.r-project.org/)?

**Comment by oseias-r-junior** [comment]
I see. I faced a hard path until was able to solve it. The CRAN version to install in (command line) ubuntu I found [here](https://cran.r-project.org/bin/linux/ubuntu/).
With R 4 installed I was able to install DESeq2 and apeglm. 
Thanks, @wckdouglas! I'll close the issue now.
