### ISSUE TITLE
Expected CPU usage and processing time

### ISSUE THREAD

**Issue by lauraluebbert** [wckdouglas/diffexpr#9]
Hi Douglas, thanks for diffexpr! I am using it to run DESeq2 on an scRNAseq dataset with 22k genes, 200 replicates, and 2 conditions (100 replicates per condition), as described in your tutorial. This uses a tremendous amount of CPU (all 48 threads on a Linux machine) and takes ~2 hours. Is this expected?

**Comment by wckdouglas** [comment]
@lauraluebbert thanks for using the package!  I have never use DESeq2 for that many replicates, but that sounds running much longer than I'd expect, were there other covariates other than the condition variable? The core of this package is running the R-version of `DESeq2` and I think `rpy2` (for converting R-object to python-object and vice versa) only add neglectable overhead.. I would encourage you to test the same comparison in an `R` environment and see whether that improves... Sorry I'm probably not being very helpful here 🥲

**Comment by lauraluebbert** [comment]
No worries, this was helpful! Feel free to close the issue. :)
